# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carpool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='dorm',
            field=models.CharField(default=0, max_length=99),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='major',
            field=models.CharField(default=0, max_length=99),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=99),
        ),
        migrations.AlterField(
            model_name='driver',
            name='photo',
            field=models.CharField(max_length=99),
        ),
    ]
