# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carpool', '0003_driver_car_model_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='phone',
            field=models.CharField(default=1, max_length=99),
            preserve_default=False,
        ),
    ]
